trigger:
- master   # or master, depending on your repo branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker-connection'       # exact name of your Docker Hub service connection
    repository: 'vyshnav123456789/vyshnav'       # your Docker Hub repo path
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'                  # adjust if Dockerfile is in a subfolder
    tags: |
      $(Build.BuildId)

